JWT_ACCESS_TOKEN_PRIVATE_KEY: KbPeShVkYp3s6v9y$B&E)H@McQfTjWnZ
JWT_REFRESH_TOKEN_PRIVATE_KEY: p3s6v9y$B&E)H@McQfTjWmZq4t7w!z%C

# DATABASE
DATABASE_HOST: localhost
DATABASE_USERNAME: postgres
DATABASE_PASSWORD: 123asd!@#

SHORTENER_URL_HOST: "http://localhost:3000"
