JWT_ACCESS_TOKEN_PRIVATE_KEY: MIICWAIBAAKBgHTgwKhNXmRYCH14Pun
JWT_REFRESH_TOKEN_PRIVATE_KEY: n8S54fnwfNzJVIT8X1EQOA47KTnEwDs

# DATABASE
DATABASE_HOST: localhost
DATABASE_USERNAME: postgres
DATABASE_PASSWORD: 123asd!@#
